services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI Web RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbt:
    # On change postgres par snowflake
    image: ghcr.io/dbt-labs/dbt-snowflake:latest 
    container_name: dbt
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app
      - ~/.dbt:/root/.dbt # Mappe ton profiles.yml local
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep infinity"]
volumes:
  rabbitmq_data: