CREATE DATABASE IF NOT EXISTS TICKETMASTER_DB;
CREATE SCHEMA IF NOT EXISTS RAW_DATA;
CREATE SCHEMA IF NOT EXISTS GOLD_DATA;
CREATE OR REPLACE TABLE TICKETMASTER_DB.RAW_DATA.EVENTS_RAW (
    ID STRING,
    NOM STRING,
    TYPE STRING,
    DATE_LOCALE DATE,
    HEURE_LOCALE TIME,
    DATE_UTC TIMESTAMP_NTZ,
    LIEU STRING,
    VILLE STRING,
    SEGMENT STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();


